version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: interview-backend
    volumes:
      - ./backend:/app
    environment:
      SECRET_KEY: dev-secret
      DEBUG: "1"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      CORS_ALLOWED_ORIGINS: "http://localhost:8080"
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: app
      DB_USER: postgres
      DB_PASSWORD: postgrespassword
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  ws-server:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    container_name: interview-ws
    volumes:
      - ./websocket:/app
    environment:
      PORT: 8001
      BACKEND_URL: http://backend:8000
    ports:
      - "8001:8001"
    working_dir: /app
    command: node server.js

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: interview-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
      - ws-server

  db:
    image: postgres:16-alpine
    container_name: interview-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
