# Generated by Django 5.2.5 on 2025-08-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interviewnote',
            old_name='candidate_name',
            new_name='interviewer_name',
        ),
    ]
