# Generated by Django 5.2.5 on 2025-09-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_notes', '0002_rename_candidate_name_interviewnote_interviewer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewnote',
            name='content',
            field=models.JSONField(),
        ),
    ]
