# Generated by Django 5.2.6 on 2025-10-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_notes', '0004_alter_interviewnote_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewnote',
            name='content',
            field=models.TextField(),
        ),
    ]
