# Generated by Django 5.2.5 on 2025-08-31 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_rooms', '0002_alter_room_options_room_created_at_room_room_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
